/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashcards;

import java.util.Date;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author Gabriel
 */
public class FlashcardsGUI extends javax.swing.JFrame {

    /**
     * Creates new form FlashcardsGUI
     */
    public FlashcardsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayLabel = new javax.swing.JLabel();
        intervalLabel = new javax.swing.JLabel();
        intervalField = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        numbersField = new javax.swing.JTextField();
        digitsLabel = new javax.swing.JLabel();
        digitsField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        notificationLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        answerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orion Flashcards");
        setBackground(new java.awt.Color(255, 255, 255));

        displayLabel.setBackground(new java.awt.Color(255, 255, 255));
        displayLabel.setFont(new java.awt.Font("Arial", 0, 120)); // NOI18N
        displayLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        displayLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        intervalLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        intervalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intervalLabel.setText("Interval (seconds)");
        intervalLabel.setToolTipText("");

        intervalField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        intervalField.setText("0");
        intervalField.setToolTipText("");
        intervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervalFieldActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        numberLabel.setText("Numbers");
        numberLabel.setToolTipText("");

        numbersField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        numbersField.setText("0");
        numbersField.setToolTipText("");

        digitsLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        digitsLabel.setText("Digits");
        digitsLabel.setToolTipText("");

        digitsField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        digitsField.setText("0");
        digitsField.setToolTipText("");

        startButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        startButton.setText("Start");
        startButton.setToolTipText("");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        notificationLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        notificationLabel.setForeground(new java.awt.Color(153, 153, 153));
        notificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notificationLabel.setText("Please fill in all the options, and then click \"Start\"");

        titleLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Orion Abacus Association");

        answerButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        answerButton.setText("Answer");
        answerButton.setEnabled(false);
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Copyright © 2015 Orion Abacus Association. Software by Gabriel Lee.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intervalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(intervalField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numbersField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digitsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(digitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationLabel)
                .addGap(18, 18, 18)
                .addComponent(displayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intervalLabel)
                    .addComponent(intervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberLabel)
                    .addComponent(numbersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digitsLabel)
                    .addComponent(digitsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton)
                    .addComponent(answerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intervalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intervalFieldActionPerformed

    int sum = 0;
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        answerButton.setEnabled(false);
        sum = 0;

        if (intervalField.getText() == "" || numbersField.getText() == "" || digitsField.getText() == "") {
            notificationLabel.setText("One or more fields are missing.");
            return;
        }

        notificationLabel.setText("Please fill in all the options, and then click \"Start\"");
        Timer timer = new Timer();
        int interval = Integer.parseInt(intervalField.getText()); // milliseconds
        
        timer.schedule(new TimerTask() {
            int count = 0;
            int limit = Integer.parseInt(numbersField.getText());
            @Override
            public void run() {
                
                if (count == limit) {
                    answerButton.setEnabled(true);
                    timer.cancel();
                    timer.purge();
                    return;
                }
                String numberString = Flashcards.generateNumber(Integer.parseInt(digitsField.getText()));
                int numberInt = Integer.parseInt(numberString);
                System.out.println("Number: " + numberInt);
                sum = sum + numberInt;
                System.out.println("The sum is now: " + sum);
                String commifiedNumber = Flashcards.commify(numberString);
                displayLabel.setText(commifiedNumber);
                count++;
            }
        }, new Date(), interval * 1000);
    }//GEN-LAST:event_startButtonActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // TODO add your handling code here:
        displayLabel.setText(Flashcards.commify(String.valueOf(sum)));
    }//GEN-LAST:event_answerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashcardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashcardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashcardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashcardsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlashcardsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JTextField digitsField;
    private javax.swing.JLabel digitsLabel;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JTextField intervalField;
    private javax.swing.JLabel intervalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel notificationLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numbersField;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
